import { StrictMode } from 'react'
import { act, render, renderHook, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it, vi } from 'vitest'
import App from './App'
import { HISTORY_KEY, type HistoryEvent } from './helpers/historyStorage'
import { useHistory } from './hooks/useHistory'
import { parseWeather } from './helpers/weatherData'
import { WeatherError } from './services/errors'
import type { WeatherService } from './services/weather'
import { deferred, fullWeather, johor, singapore } from './test/weatherFixtures'
import type { Weather } from './types/weather'

const saved = (id = 'original', location = johor): HistoryEvent => ({ id, location, completedAt: '2026-10-02T04:00:00.000Z' })
const seed = (records: HistoryEvent[]) => localStorage.setItem(HISTORY_KEY, JSON.stringify({ version: 1, records }))
const rows = () => within(screen.getByRole('region', { name: 'Search History' })).queryAllByRole('listitem')
const stored = (): HistoryEvent[] => JSON.parse(localStorage.getItem(HISTORY_KEY)!).records
const serviceFor = (): WeatherService => ({ findLocations: vi.fn().mockResolvedValue([johor]),
  getWeather: vi.fn().mockResolvedValue(parseWeather(fullWeather(), johor)) })
afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers() })

describe('durable history integration', () => {
  it('ends a stalled lock wait honestly and retries pending changes on the next mutation', async () => {
    vi.useFakeTimers()
    const write = vi.spyOn(Storage.prototype, 'setItem')
    const request = vi.spyOn(navigator.locks, 'request').mockImplementation((_name, options) => new Promise((_resolve, reject) => {
      options.signal?.addEventListener('abort', () => reject(new DOMException('', 'AbortError')), { once: true })
    }))
    const hook = renderHook(() => useHistory())
    act(() => hook.result.current.append(johor))
    expect(hook.result.current.records).toHaveLength(1)
    expect(hook.result.current.warning).toContain('Saving history')
    await act(async () => { await vi.advanceTimersByTimeAsync(2_000) })
    expect(hook.result.current.warning).toContain('only for this session')
    expect(write).not.toHaveBeenCalled()
    request.mockRestore()
    await act(async () => hook.result.current.remove(hook.result.current.records[0]!.id))
    expect(stored()).toEqual([])
    expect(hook.result.current.warning).toBe('')
  })
  it('aborts queued locking on unmount without writing after the hook is gone', async () => {
    const write = vi.spyOn(Storage.prototype, 'setItem')
    let signal: AbortSignal | undefined
    vi.spyOn(navigator.locks, 'request').mockImplementation((_name, options) => new Promise((_resolve, reject) => {
      signal = options.signal
      signal?.addEventListener('abort', () => reject(new DOMException('', 'AbortError')), { once: true })
    }))
    const hook = renderHook(() => useHistory())
    act(() => hook.result.current.append(johor))
    await act(async () => hook.unmount())
    expect(signal?.aborted).toBe(true)
    expect(write).not.toHaveBeenCalled()
  })
  it('retains pending changes when a later storage read fails without overwriting unseen history', async () => {
    seed([saved()])
    const hook = renderHook(() => useHistory())
    const read = vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new DOMException('', 'SecurityError') })
    const write = vi.spyOn(Storage.prototype, 'setItem')
    await act(async () => hook.result.current.append(johor))
    expect(hook.result.current.records).toHaveLength(2)
    expect(hook.result.current.warning).toContain('only for this session')
    expect(write).not.toHaveBeenCalled()
    read.mockRestore()
    expect(stored()).toEqual([saved()])
    await act(async () => hook.result.current.append(singapore))
    expect(stored()).toHaveLength(3)
    expect(stored()[2]).toEqual(saved())
    expect(hook.result.current.warning).toBe('')
  })
  it('reads the latest saved records for every mutation even without a storage event', async () => {
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    seed([saved('other-tab')])
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await waitFor(() => expect(stored()).toHaveLength(2))
    expect(stored()[1]?.id).toBe('other-tab')
    seed([stored()[0]!])
    await user.click(within(rows()[0]!).getByRole('button', { name: /Search again/ }))
    await waitFor(() => expect(stored()).toHaveLength(2))
    expect(stored().some(event => event.id === 'other-tab')).toBe(false)
  })
  it('handles delayed history events using current storage and ignores unrelated storage', () => {
    seed([saved('old')])
    render(<App service={serviceFor()} />)
    seed([saved('latest')])
    act(() => window.dispatchEvent(new StorageEvent('storage', {
      key: HISTORY_KEY, newValue: JSON.stringify({ version: 1, records: [saved('old')] }), storageArea: localStorage,
    })))
    expect(rows()[0]).toHaveAttribute('data-history-id', 'latest')
    seed([])
    act(() => window.dispatchEvent(new StorageEvent('storage', { key: 'unrelated', storageArea: localStorage })))
    expect(rows()).toHaveLength(1)
    act(() => window.dispatchEvent(new StorageEvent('storage', { key: HISTORY_KEY, storageArea: sessionStorage })))
    expect(rows()).toHaveLength(1)
    act(() => window.dispatchEvent(new StorageEvent('storage', { key: null, storageArea: localStorage })))
    expect(rows()).toHaveLength(0)
  })
  it.each(['missing', 'rejected'] as const)('keeps history session-only if safe locking is %s', async mode => {
    seed([saved()])
    const write = vi.spyOn(Storage.prototype, 'setItem')
    if (mode === 'missing') Object.defineProperty(navigator, 'locks', { configurable: true, value: undefined })
    else vi.spyOn(navigator.locks, 'request').mockRejectedValue(new DOMException('', 'SecurityError'))
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await waitFor(() => expect(rows()).toHaveLength(2))
    await waitFor(() => expect(screen.getByRole('status')).toHaveTextContent('only for this session'))
    expect(write).not.toHaveBeenCalled()
    expect(stored()).toEqual([saved()])
    await user.click(within(rows()[1]!).getByRole('button', { name: /Delete/ }))
    expect(rows()).toHaveLength(1)
    expect(stored()).toEqual([saved()])
  })
  it('rebases unsaved additions and deletion on another tab update before retrying a failed write', async () => {
    seed([saved('deleted')])
    const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('', 'QuotaExceededError') })
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await waitFor(() => expect(rows()).toHaveLength(2))
    const localId = rows()[0]!.getAttribute('data-history-id')
    await user.click(within(rows()[1]!).getByRole('button', { name: /Delete/ }))
    write.mockRestore()
    seed([saved('remote'), saved('deleted')])
    act(() => window.dispatchEvent(new StorageEvent('storage', { key: HISTORY_KEY, storageArea: localStorage })))
    expect(rows().map(row => row.getAttribute('data-history-id'))).toEqual([localId, 'remote'])
    expect(screen.getByRole('status')).toHaveTextContent('only for this session')
    await user.click(within(rows()[1]!).getByRole('button', { name: /Delete/ }))
    await waitFor(() => expect(stored().map(event => event.id)).toEqual([localId]))
    expect(screen.getByRole('status')).not.toHaveTextContent('only for this session')
  })
  it('does not overwrite unseen records when reads fail but writes would succeed', async () => {
    seed([saved()])
    const read = vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new DOMException('', 'SecurityError') })
    const write = vi.spyOn(Storage.prototype, 'setItem')
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    expect(rows()).toHaveLength(0)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await screen.findByRole('region', { name: 'Current weather' })
    expect(rows()).toHaveLength(1)
    expect(write).not.toHaveBeenCalled()
    expect(screen.getByRole('status')).toHaveTextContent('only for this session')
    read.mockRestore()
    expect(stored()).toEqual([saved()])
  })
  it('hydrates without writes or automatic weather and commits once under StrictMode', async () => {
    seed([saved()])
    const write = vi.spyOn(Storage.prototype, 'setItem')
    const service = serviceFor()
    const user = userEvent.setup()
    const view = render(<StrictMode><App service={service} /></StrictMode>)
    expect(rows()).toHaveLength(1)
    expect(write).not.toHaveBeenCalled()
    expect(service.getWeather).not.toHaveBeenCalled()
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await screen.findByRole('region', { name: 'Current weather' })
    expect(rows()).toHaveLength(2)
    expect(stored()[1]).toEqual(saved())
    expect(stored()[0]?.id).not.toBe('original')
    expect(write).toHaveBeenCalledTimes(1)
    const snapshot = stored()
    view.unmount()
    render(<StrictMode><App service={service} /></StrictMode>)
    expect(stored()).toEqual(snapshot)
    expect(rows()).toHaveLength(2)
    expect(screen.queryByRole('region', { name: 'Current weather' })).not.toBeInTheDocument()
    expect(service.getWeather).toHaveBeenCalledTimes(1)
  })
  it('preserves equal-time insertion order and deletes only the chosen repeated event', async () => {
    seed([saved('first'), saved('second'), saved('third')])
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    await user.type(screen.getByRole('textbox'), 'unrelated text')
    await user.click(within(rows()[1]!).getByRole('button', { name: /Delete/ }))
    expect(stored().map(row => row.id)).toEqual(['first', 'third'])
    expect(within(rows()[1]!).getByRole('button', { name: /Delete/ })).toHaveFocus()
    expect(screen.getByRole('textbox')).toHaveValue('unrelated text')
    await user.click(within(rows()[1]!).getByRole('button', { name: /Delete/ }))
    expect(within(rows()[0]!).getByRole('button', { name: /Delete/ })).toHaveFocus()
    await user.click(within(rows()[0]!).getByRole('button', { name: /Delete/ }))
    expect(screen.getByText('No Record')).toBeVisible()
    expect(screen.getByRole('textbox')).toHaveFocus()
    expect(stored()).toEqual([])
  })
  it.each(['success', 'failure', 'cancel'] as const)('deleting an active replay source preserves request ownership: %s', async outcome => {
    seed([saved()])
    const pending = deferred<Weather>()
    const service = { findLocations: vi.fn(), getWeather: vi.fn<WeatherService['getWeather']>(() => pending.promise) }
    const user = userEvent.setup()
    render(<App service={service} />)
    await user.type(screen.getByRole('textbox'), 'invalid, country')
    const replay = within(rows()[0]!).getByRole('button', { name: /Search again/ })
    await user.click(replay)
    expect(service.getWeather).toHaveBeenCalledWith(johor, expect.any(AbortSignal))
    expect(service.findLocations).not.toHaveBeenCalled()
    expect(screen.getByRole('textbox')).toHaveAttribute('readonly')
    expect(screen.getByRole('button', { name: 'Search' })).toBeDisabled()
    expect(replay).toHaveTextContent('Searching...')
    expect(document.querySelectorAll('.search-indicator')).toHaveLength(1)
    await user.click(within(rows()[0]!).getByRole('button', { name: /Delete/ }))
    expect(document.querySelectorAll('.search-indicator')).toHaveLength(0)
    expect(screen.getByRole('status')).toHaveTextContent('Fetching weather for Johor Bahru, MY...')
    expect(service.getWeather.mock.calls[0]?.[1].aborted).toBe(false)
    expect(stored()).toEqual([])
    if (outcome === 'cancel') await user.click(screen.getByRole('button', { name: 'Clear' }))
    await act(async () => {
      if (outcome === 'failure') pending.reject(new WeatherError('Replay failed.'))
      else pending.resolve(parseWeather(fullWeather(), johor))
    })
    await waitFor(() => expect(screen.getByRole('button', { name: 'Search' })).toBeEnabled())
    if (outcome === 'success') {
      expect(rows()).toHaveLength(1)
      expect(stored()[0]?.id).not.toBe('original')
      expect(stored()[0]?.completedAt).not.toBe(saved().completedAt)
      expect(screen.getByRole('textbox')).toHaveValue('invalid, country')
    } else {
      expect(rows()).toHaveLength(0)
      expect(stored()).toEqual([])
    }
  })
  it('replay replaces candidate waiting, locks rapid submissions, and rejects stale selection', async () => {
    seed([saved()])
    const pending = deferred<Weather>()
    const service: WeatherService = { findLocations: vi.fn().mockResolvedValue([johor, singapore]), getWeather: vi.fn(() => pending.promise) }
    const user = userEvent.setup()
    render(<App service={service} />)
    await user.type(screen.getByRole('textbox'), 'City{Enter}')
    const candidate = await screen.findByRole('button', { name: /Singapore, SG/ })
    expect(stored()).toEqual([saved()])
    const replay = within(rows()[0]!).getByRole('button', { name: /Search again/ })
    await user.click(replay)
    act(() => { replay.click(); candidate.click(); replay.click() })
    expect(service.getWeather).toHaveBeenCalledTimes(1)
    expect(service.getWeather).toHaveBeenCalledWith(johor, expect.any(AbortSignal))
    expect(screen.queryByRole('heading', { name: 'Choose a location' })).not.toBeInTheDocument()
    await act(async () => pending.resolve(parseWeather(fullWeather(), johor)))
    expect(rows()).toHaveLength(2)
  })
  it('retains successful history after Clear and leaves the card intact on deletion', async () => {
    const user = userEvent.setup()
    render(<App service={serviceFor()} />)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await screen.findByRole('region', { name: 'Current weather' })
    await user.click(within(rows()[0]!).getByRole('button', { name: /Delete/ }))
    expect(screen.getByRole('region', { name: 'Current weather' })).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Search' }))
    await waitFor(() => expect(rows()).toHaveLength(1))
    const snapshot = stored()
    await user.click(screen.getByRole('button', { name: 'Clear' }))
    expect(stored()).toEqual(snapshot)
    expect(rows()).toHaveLength(1)
  })
  it('keeps degraded success and its storage failure warning independently, including after Clear', async () => {
    const user = userEvent.setup()
    const write = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new DOMException('', 'QuotaExceededError') })
    const service = serviceFor()
    vi.mocked(service.getWeather).mockResolvedValue(parseWeather({ main: { temp: 0 }, weather: [{ main: 'Clouds' }] }, johor))
    render(<App service={service} />)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await screen.findByRole('region', { name: 'Current weather' })
    expect(rows()).toHaveLength(1)
    expect(screen.getAllByRole('status')).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('Some weather details are unavailable.')
    expect(screen.getByRole('status')).toHaveTextContent('only for this session')
    await user.click(screen.getByRole('button', { name: 'Clear' }))
    expect(rows()).toHaveLength(1)
    expect(screen.getByRole('status')).toHaveTextContent('only for this session')
    write.mockRestore()
    await user.click(within(rows()[0]!).getByRole('button', { name: /Delete/ }))
    expect(screen.getByRole('status')).toBeEmptyDOMElement()
    expect(stored()).toEqual([])
  })
  it('canceling weather response processing prevents history commit even after a replacement', async () => {
    const old = deferred<Weather>()
    const service = serviceFor()
    vi.mocked(service.getWeather).mockReturnValueOnce(old.promise)
    const user = userEvent.setup()
    render(<App service={service} />)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await waitFor(() => expect(service.getWeather).toHaveBeenCalledTimes(1))
    await user.click(screen.getByRole('button', { name: 'Clear' }))
    expect(rows()).toHaveLength(0)
    await user.type(screen.getByRole('textbox'), 'Johor{Enter}')
    await screen.findByRole('region', { name: 'Current weather' })
    const snapshot = stored()
    await act(async () => old.resolve(parseWeather(fullWeather(), singapore)))
    expect(stored()).toEqual(snapshot)
    expect(rows()).toHaveLength(1)
  })
})
